version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cibrxpass123
      MYSQL_DATABASE: csrf_soru
      MYSQL_USER: urbatek_user
      MYSQL_PASSWORD: cibrxpass123
    ports:
      - "4607:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - csrf_network

  admin:
    build:
      context: ./admin
    container_name: admin_service
    restart: always
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_USER: urbatek_user
      DB_PASSWORD: cibrxpass123
      DB_NAME: csrf_soru
    ports:
      - "1453:3000"
    depends_on:
      - mysql
    networks:
      - csrf_network

  portal:
    build:
      context: ./portal
    container_name: portal_service
    restart: always
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_USER: urbatek_user
      DB_PASSWORD: cibrxpass123
      DB_NAME: csrf_soru
    ports:
      - "3002:3000"
    depends_on:
      - mysql
    networks:
      - csrf_network

networks:
  csrf_network:
    driver: bridge
